
/**
 ** Author: BRYLLE NUNEZ
 ** Date: December 20, 2021
 ** Description: The program calculates and displays the:
 ** 1) Number of milk cartons needed;
 ** 2) Milk's total amount of production cost;
 ** 3) Milk's total amount of profit generated;
 ** Given the milk carton capacity, profit of each carton, and the cost of each liter of milk.
 */
import javax.swing.JOptionPane;

public class Milk {
    public static void main(String[] args) {
        // VARIABLE DECLARATION
        String userInput; // String variable to be used for prompt
        final double MILK_CARTON_CAPACITY = 3.78, PROFIT_CARTON = 13.5; // Named constants (given from the problem)
        final int ONE_LITER_COST = 19;
        double amountOfMilkInLiters, milkCartons; // New variable to be used as a storage for user's input;
        int milkProductionCost, milkProductionProfit; // Variables for computation

        // PROMPT BOX (1)
        userInput = JOptionPane.showInputDialog(null, "Enter the amount of milk produced in liters.",
                "User Prompt: Amount of Milk", JOptionPane.INFORMATION_MESSAGE); // Asks the user the amount of milk in
                                                                                 // liters
        amountOfMilkInLiters = Double.parseDouble(userInput); // Converts user's answer into a double

        milkCartons = (amountOfMilkInLiters / MILK_CARTON_CAPACITY); // From the user's input, the number of
                                                                     // milk cartons is computed

        // COST/PROFIT COMPUTATION (3)
        milkProductionCost = (int) (amountOfMilkInLiters * ONE_LITER_COST); // Computes the cost from producing milk,
                                                                            // which is the cost per liter in each
                                                                            // amount of milk
        milkProductionProfit = (int) (milkCartons * PROFIT_CARTON); // Computes the profit generated by the number of
                                                                    // milk cartons used and its amount of profit

        // DISPLAY BOX (2),(3)
        JOptionPane.showMessageDialog(null,
                "The estimated number of cartons needed to hold your milk is " + Math.round(milkCartons) + " carton/s."
                        + "\nThe total cost of producing the milk is PHP " + milkProductionCost + "."
                        + "\nThe total profit from producing the milk is PHP " + milkProductionProfit + ".",
                "Milk Cartons, Cost, and Profit Calculated",
                JOptionPane.INFORMATION_MESSAGE); // Displaying the outputs (2) and (3) from the task
    }
}